### ISSUE TITLE
Maven build fails in Azure function example application

### ISSUE THREAD

**Issue by graemerocher** [micronaut-projects/micronaut-azure#1]
When running the Maven build for the Azure Function sample application:

```
./mvn clean package
```

The build fails with the following error:

```
[ERROR] Failed to execute goal com.microsoft.azure:azure-functions-maven-plugin:1.3.4:package (package-functions) on project azure-functions-example: Can't resolve member named invoke for class example.Function -> [Help 1]
[ERROR]
```

The stacktrace is:

```
Caused by: org.reflections.ReflectionsException: Can't resolve member named invoke for class example.Function
	at org.reflections.util.Utils.getMemberFromDescriptor(Utils.java:94)
	at org.reflections.util.Utils.getMethodsFromDescriptors(Utils.java:101)
	at org.reflections.Reflections.getMethodsAnnotatedWith(Reflections.java:482)
	at com.microsoft.azure.maven.function.handlers.AnnotationHandlerImpl.findFunctions(AnnotationHandlerImpl.java:50)
	at com.microsoft.azure.maven.function.PackageMojo.findAnnotatedMethods(PackageMojo.java:135)
	at com.microsoft.azure.maven.function.PackageMojo.doExecute(PackageMojo.java:87)
	at com.microsoft.azure.maven.AbstractAzureMojo.execute(AbstractAzureMojo.java:309)
```

**Comment by brunoborges** [comment]
Can you post the project source?

**Comment by graemerocher** [comment]
Sorry it is here https://github.com/micronaut-projects/micronaut-azure/tree/master/examples/azure-functions-example

**Comment by graemerocher** [comment]
Seems like it is a dependency issue maybe? Seems like some method is not visible somehow

**Comment by graemerocher** [comment]
Associated issue report https://github.com/microsoft/azure-maven-plugins/issues/1051
