### ISSUE TITLE
Support multiple triggers

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-azure#198]
Local Operating System : MacOs. 
### Requisites

- You have the latest [Azure Functions Core Tools](https://docs.microsoft.com/en-us/azure/azure-functions/functions-run-local?tabs=macos%2Ccsharp%2Cbash#install-the-azure-functions-core-tools) installed. 

### Steps to reproduce

- Generate a Micronaut application using `azure-function` as feature

```
mn create-app example.micronaut.demo --feature=azure-function
```

### Code

In addition to: 

```java
package com.example;
import java.util.*;
import com.microsoft.azure.functions.annotation.*;
import com.microsoft.azure.functions.*;
import io.micronaut.azure.function.http.AzureHttpFunction;

public class Function extends AzureHttpFunction {
    @FunctionName("ExampleTrigger")
    public HttpResponseMessage invoke(
            @HttpTrigger(
                name = "req",
                methods = {HttpMethod.GET, HttpMethod.POST},
                route = "{*route}",
                authLevel = AuthorizationLevel.ANONYMOUS)
                HttpRequestMessage<Optional<String>> request,
                final ExecutionContext context) {
        return super.route(request, context);
    }
}
```

```java
package com.example;

import io.micronaut.http.annotation.*;
import io.micronaut.http.annotation.Produces;
import io.micronaut.http.MediaType;
import io.micronaut.core.annotation.Introspected;

@Controller("/demo")
public class DemoController {

    @Produces(MediaType.TEXT_PLAIN)
    @Get
    public String index() {
        return "Example Response";
    }

    @Post
    public SampleReturnMessage postMethod(@Body SampleInputMessage inputMessage){
      SampleReturnMessage retMessage = new SampleReturnMessage();
      retMessage.setReturnMessage("Hello " + inputMessage.getName() + ", thank you for sending the message");
      return retMessage;
    }
}

@Introspected
class SampleInputMessage{
    private String name;

    public SampleInputMessage() {
    }

    public SampleInputMessage(String name) {
        this.name = name;
    }

    public String getName() {
        return name;
    }
    public void setName(String name) {
        this.name = name;
    }
}

@Introspected
class SampleReturnMessage{
    private String returnMessage;
    public String getReturnMessage() {
        return returnMessage;
    }
    public void setReturnMessage(String returnMessage) {
        this.returnMessage = returnMessage;
    }
}
```

Add a new `AzureFunction` for a cron job: 

```java
package com.example;

import com.microsoft.azure.functions.ExecutionContext;
import com.microsoft.azure.functions.annotation.FunctionName;
import com.microsoft.azure.functions.annotation.TimerTrigger;
import io.micronaut.azure.function.AzureFunction;

public class CronFunction extends AzureFunction {
    @FunctionName("CronTrigger")
    public String echo(
            @TimerTrigger(name = "req", dataType = "string", schedule = "0 */2 * * * *") String req, // every 2 minutes
            ExecutionContext context) {
        if (context != null) {
            System.out.println("TimeTrigger Function: " + getClass().getName());
            context.getLogger().info("TimeTrigger Function: " + getClass().getName());
        }
        return String.format(req);
    }
}
```

Edit `local.settings.json`

Replace: 

```
    "AzureWebJobsStorage": "", 
```

 with: 

```
    "AzureWebJobsStorage": "UseDevelopmentStorage=true",
```

### Run the function

- [Install Azurite](https://docs.microsoft.com/en-us/azure/storage/common/storage-use-azurite) for time trigger.

- Start Azurite
```
% azurite
Azurite Blob service is starting at http://127.0.0.1:10000
Azurite Blob service is successfully listening at http://127.0.0.1:10000
Azurite Queue service is starting at http://127.0.0.1:10001
Azurite Queue service is successfully listening at http://127.0.0.1:10001
Azurite Table service is starting at http://127.0.0.1:10002
Azurite Table service is successfully listening at http://127.0.0.1:10002
```

- Run the function locally `./gradlew azureFunctionsRun`
and you will get an error: 

```
[2021-05-08T05:50:38.099Z] Listening for transport dt_socket at address: 5005
[2021-05-08T05:50:38.115Z] 07:50:38.112 [pool-2-thread-1] INFO  i.m.context.env.DefaultEnvironment - Established active environments: [azure, function]
[2021-05-08T05:50:38.115Z] 07:50:38.112 [pool-2-thread-2] INFO  i.m.context.env.DefaultEnvironment - Established active environments: [azure, function]
[2021-05-08T05:50:38.145Z] 07:50:38.144 [pool-2-thread-2] ERROR i.m.azure.function.AzureFunction - Error initializing Azure function: null:azureFunctionsRun
[2021-05-08T05:50:38.145Z] java.nio.file.FileSystemAlreadyExistsException: null
[2021-05-08T05:50:38.145Z]      at jdk.zipfs/jdk.nio.zipfs.ZipFileSystemProvider.newFileSystem(ZipFileSystemProvider.java:102)
[2021-05-08T05:50:38.145Z]      at java.base/java.nio.file.FileSystems.newFileSystem(FileSystems.java:337)
[2021-05-08T05:50:38.145Z]      at io.micronaut.core.io.scan.DefaultClassPathResourceLoader.getResourceAsStream(DefaultClassPathResourceLoader.java:92)
[2021-05-08T05:50:38.145Z]      at io.micronaut.context.env.DefaultEnvironment.getResourceAsStream(DefaultEnvironment.java:311)
[2021-05-08T05:50:38.145Z]      at io.micronaut.context.env.AbstractPropertySourceLoader.readInput(AbstractPropertySourceLoader.java:127)
[2021-05-08T05:50:38.145Z]      at io.micronaut.context.env.AbstractPropertySourceLoader.loadProperties(AbstractPropertySourceLoader.java:96)
[2021-05-08T05:50:38.145Z]      at io.micronaut.context.env.AbstractPropertySourceLoader.load(AbstractPropertySourceLoader.java:68)
[2021-05-08T05:50:38.145Z]      at io.micronaut.context.env.AbstractPropertySourceLoader.load(AbstractPropertySourceLoader.java:55)
[2021-05-08T05:50:38.145Z]      at io.micronaut.context.env.DefaultEnvironment.loadPropertySourceFromLoader(DefaultEnvironment.java:569)
[2021-05-08T05:50:38.145Z]      at io.micronaut.context.env.DefaultEnvironment.readPropertySourceList(DefaultEnvironment.java:502)
[2021-05-08T05:50:38.145Z]      at io.micronaut.context.env.DefaultEnvironment.readPropertySourceList(DefaultEnvironment.java:488)
[2021-05-08T05:50:38.145Z]      at io.micronaut.context.DefaultApplicationContext$RuntimeConfiguredEnvironment.readPropertySourceList(DefaultApplicationContext.java:749)
[2021-05-08T05:50:38.145Z]      at io.micronaut.context.env.DefaultEnvironment.readPropertySources(DefaultEnvironment.java:392)
[2021-05-08T05:50:38.145Z]      at io.micronaut.context.env.DefaultEnvironment.start(DefaultEnvironment.java:254)
[2021-05-08T05:50:38.145Z]      at io.micronaut.context.DefaultApplicationContext$RuntimeConfiguredEnvironment.start(DefaultApplicationContext.java:721)
[2021-05-08T05:50:38.146Z]      at io.micronaut.context.DefaultApplicationContext$RuntimeConfiguredEnvironment.start(DefaultApplicationContext.java:689)
[2021-05-08T05:50:38.146Z]      at io.micronaut.context.DefaultApplicationContext.startEnvironment(DefaultApplicationContext.java:227)
[2021-05-08T05:50:38.146Z]      at io.micronaut.context.DefaultApplicationContext.start(DefaultApplicationContext.java:179)
[2021-05-08T05:50:38.146Z]      at io.micronaut.azure.function.AzureFunction.startApplicationContext(AzureFunction.java:72)
[2021-05-08T05:50:38.146Z]      at io.micronaut.azure.function.AzureFunction.<clinit>(AzureFunction.java:40)
[2021-05-08T05:50:38.146Z]      at java.base/java.lang.Class.forName0(Native Method)
[2021-05-08T05:50:38.146Z]      at java.base/java.lang.Class.forName(Class.java:398)
[2021-05-08T05:50:38.146Z]      at com.microsoft.azure.functions.worker.broker.EnhancedJavaMethodExecutorImpl.getContainingClass(EnhancedJavaMethodExecutorImpl.java:63)
[2021-05-08T05:50:38.146Z]      at com.microsoft.azure.functions.worker.broker.EnhancedJavaMethodExecutorImpl.<init>(EnhancedJavaMethodExecutorImpl.java:22)
[2021-05-08T05:50:38.146Z]      at com.microsoft.azure.functions.worker.broker.FactoryJavaMethodExecutor.getJavaMethodExecutor(FactoryJavaMethodExecutor.java:20)
[2021-05-08T05:50:38.146Z]      at com.microsoft.azure.functions.worker.broker.JavaFunctionBroker.loadMethod(JavaFunctionBroker.java:38)
[2021-05-08T05:50:38.146Z]      at com.microsoft.azure.functions.worker.handler.FunctionLoadRequestHandler.execute(FunctionLoadRequestHandler.java:27)
[2021-05-08T05:50:38.146Z]      at com.microsoft.azure.functions.worker.handler.FunctionLoadRequestHandler.execute(FunctionLoadRequestHandler.java:9)
[2021-05-08T05:50:38.146Z]      at com.microsoft.azure.functions.worker.handler.MessageHandler.handle(MessageHandler.java:45)
[2021-05-08T05:50:38.146Z]      at com.microsoft.azure.functions.worker.JavaWorkerClient$StreamingMessagePeer.lambda$onNext$0(JavaWorkerClient.java:92)
[2021-05-08T05:50:38.146Z]      at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[2021-05-08T05:50:38.146Z]      at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[2021-05-08T05:50:38.146Z]      at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[2021-05-08T05:50:38.146Z]      at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[2021-05-08T05:50:38.146Z]      at java.base/java.lang.Thread.run(Thread.java:829)
```

It seems we currently don't support having multiple classes extending `AzureFunction` with  `@FunctionName` methods. 

It seems both triggers work fine in the Azure Portal: 

<img width="1644" alt="Screenshot 2021-05-10 at 19 14 39" src="https://user-images.githubusercontent.com/864788/117698549-23f69100-b1c4-11eb-8a6e-4cf5710657bc.png">
<img width="1994" alt="Screenshot 2021-05-10 at 19 15 08" src="https://user-images.githubusercontent.com/864788/117698556-25c05480-b1c4-11eb-83f9-c21cb61167cc.png">

**Comment by sdelamo** [comment]
I tried having a single class extending `AzureFunction` with two methods annotated with `FunctionName`. e.g. : 

```java
package com.example;
import java.util.*;
import com.microsoft.azure.functions.annotation.*;
import com.microsoft.azure.functions.*;
import io.micronaut.azure.function.http.AzureHttpFunction;

public class Function extends AzureHttpFunction {
    @FunctionName("ExampleTrigger")
    public HttpResponseMessage invoke(
            @HttpTrigger(
                name = "req",
                methods = {HttpMethod.GET, HttpMethod.POST},
                route = "{*route}",
                authLevel = AuthorizationLevel.ANONYMOUS)
                HttpRequestMessage<Optional<String>> request,
                final ExecutionContext context) {
        return super.route(request, context);
    }

    @FunctionName("CronTrigger")
    public String echo(
            @TimerTrigger(name = "req", dataType = "string", schedule = "0 */2 * * * *") String req, // every 2 minutes
            ExecutionContext context) {
        if (context != null) {
            System.out.println("TimeTrigger Function: " + getClass().getName());
            context.getLogger().info("TimeTrigger Function: " + getClass().getName());
        }
        return String.format(req);
    }
}
```

but I got the same error.
