### ISSUE TITLE
Exception thrown when handling parallel requests

### ISSUE THREAD

**Issue by janjongerden-tomtom** [micronaut-projects/micronaut-azure#387]
### Expected Behavior

Parallel requests should be handled without errors

### Actual Behaviour

When micronaut is still busy with a request, a second request will fail with a 500 and the following stacktrace:

```
System.Private.CoreLib: Exception while executing function: Functions.Search. System.Private.CoreLib: Result: Failure
Exception: IllegalArgumentException: Cannot destroy non-singleton bean using bean definition! Use 'destroyBean(BeanRegistration)` or `destroyBean(<BeanInstance>)`.
Stack: java.lang.reflect.InvocationTargetException
     at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     at java.base/java.lang.reflect.Method.invoke(Method.java:566)
     at com.microsoft.azure.functions.worker.broker.JavaMethodInvokeInfo.invoke(JavaMethodInvokeInfo.java:22)
     at com.microsoft.azure.functions.worker.broker.EnhancedJavaMethodExecutorImpl.execute(EnhancedJavaMethodExecutorImpl.java:55)
     at com.microsoft.azure.functions.worker.broker.JavaFunctionBroker.invokeMethod(JavaFunctionBroker.java:61)
     at com.microsoft.azure.functions.worker.handler.InvocationRequestHandler.execute(InvocationRequestHandler.java:33)
     at com.microsoft.azure.functions.worker.handler.InvocationRequestHandler.execute(InvocationRequestHandler.java:10)
     at com.microsoft.azure.functions.worker.handler.MessageHandler.handle(MessageHandler.java:45)
     at com.microsoft.azure.functions.worker.JavaWorkerClient$StreamingMessagePeer.lambda$onNext$0(JavaWorkerClient.java:92)
     at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
     at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
     at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
     at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
     at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.IllegalArgumentException: Cannot destroy non-singleton bean using bean definition! Use 'destroyBean(BeanRegistration)` or `destroyBean(<BeanInstance>)`.
     at io.micronaut.context.DefaultBeanContext.destroyBean(DefaultBeanContext.java:1114)
     at java.base/java.util.Optional.map(Optional.java:265)
     at io.micronaut.context.DefaultBeanContext.destroyBean(DefaultBeanContext.java:1076)
     at io.micronaut.context.DefaultBeanContext.destroyBean(DefaultBeanContext.java:1102)
     at io.micronaut.azure.function.http.AzureHttpFunction.route(AzureHttpFunction.java:131)
     at com.tomtom.Function.invoke(Function.java:38)
     ... 16 more
```

### Steps To Reproduce

- created an application using [this guide](https://guides.micronaut.io/latest/micronaut-azure-http-functions-gradle-groovy.html). 
- start it with `./gradlew azureFunctionsRun`
- fire two requests at the same time
- the first request succeeds, the second request will return `500 Internal Server Error` and the application logs this stacktrace

```
System.Private.CoreLib: Exception while executing function: Functions.Search. System.Private.CoreLib: Result: Failure
Exception: IllegalArgumentException: Cannot destroy non-singleton bean using bean definition! Use 'destroyBean(BeanRegistration)` or `destroyBean(<BeanInstance>)`.
Stack: java.lang.reflect.InvocationTargetException
     at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     at java.base/java.lang.reflect.Method.invoke(Method.java:566)
     at com.microsoft.azure.functions.worker.broker.JavaMethodInvokeInfo.invoke(JavaMethodInvokeInfo.java:22)
     at com.microsoft.azure.functions.worker.broker.EnhancedJavaMethodExecutorImpl.execute(EnhancedJavaMethodExecutorImpl.java:55)
     at com.microsoft.azure.functions.worker.broker.JavaFunctionBroker.invokeMethod(JavaFunctionBroker.java:61)
     at com.microsoft.azure.functions.worker.handler.InvocationRequestHandler.execute(InvocationRequestHandler.java:33)
     at com.microsoft.azure.functions.worker.handler.InvocationRequestHandler.execute(InvocationRequestHandler.java:10)
     at com.microsoft.azure.functions.worker.handler.MessageHandler.handle(MessageHandler.java:45)
     at com.microsoft.azure.functions.worker.JavaWorkerClient$StreamingMessagePeer.lambda$onNext$0(JavaWorkerClient.java:92)
     at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
     at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
     at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
     at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
     at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.IllegalArgumentException: Cannot destroy non-singleton bean using bean definition! Use 'destroyBean(BeanRegistration)` or `destroyBean(<BeanInstance>)`.
     at io.micronaut.context.DefaultBeanContext.destroyBean(DefaultBeanContext.java:1114)
     at java.base/java.util.Optional.map(Optional.java:265)
     at io.micronaut.context.DefaultBeanContext.destroyBean(DefaultBeanContext.java:1076)
     at io.micronaut.context.DefaultBeanContext.destroyBean(DefaultBeanContext.java:1102)
     at io.micronaut.azure.function.http.AzureHttpFunction.route(AzureHttpFunction.java:131)
     at com.tomtom.Function.invoke(Function.java:38)
     ... 16 more
```

### Version

micronaut-azure 3.5.0 , from gradle plugin io.micronaut.application 3.6.2

**Comment by thomasmillercf** [comment]
Yea this is a real pain, spent a good few hours to work out this was the cause of my 500s.
