### ISSUE TITLE
AzureHttpFunction: Azure Exception for HTTP POST 

### ISSUE THREAD

**Issue by mynecker** [micronaut-projects/micronaut-azure#5]
Azure can't invoke Micronaut AzureHttpFunction with `HttpRequestMessage<java.util.Optional<byte[]>>` as input parameter.

### Steps to Reproduce

1. Pull sample from azure-function-demo-application
2. Deploy function into your Azure subscription / resource group
3. Invoke HTTP POST http://<your-app-name>.azurewebsites.net/api/hello/post
4. HTTP-500 from Azure function 

### Result

Exception copied from Azure Function Monitoring
```
Result: Failure Exception: ClassCastException: 
Cannot convert com.microsoft.azure.functions.worker.binding.RpcHttpRequestDataSource@49e9c63a
to type com.microsoft.azure.functions.HttpRequestMessage<java.util.Optional<byte[]>> 
Stack: java.lang.ClassCastException: Cannot convert com.microsoft.azure.functions.worker.binding.RpcHttpRequestDataSource@49e9c63a
to type com.microsoft.azure.functions.HttpRequestMessage<java.util.Optional<byte[]>> 
at com.microsoft.azure.functions.worker.binding.DataOperations.generalAssignment(DataOperations.java:191) 
at com.microsoft.azure.functions.worker.binding.DataOperations.apply(DataOperations.java:120) 
at com.microsoft.azure.functions.worker.binding.DataSource.computeByType(DataSource.java:56) 
at com.microsoft.azure.functions.worker.binding.RpcHttpRequestDataSource.computeByType(RpcHttpRequestDataSource.java:20) 
at com.microsoft.azure.functions.worker.binding.DataSource.computeByName(DataSource.java:42) 
at com.microsoft.azure.functions.worker.binding.RpcHttpRequestDataSource.computeByName(RpcHttpRequestDataSource.java:20) 
at com.microsoft.azure.functions.worker.binding.BindingDataStore.getDataByName(BindingDataStore.java:55) 
at com.microsoft.azure.functions.worker.broker.ParameterResolver.resolve(ParameterResolver.java:59) 
at com.microsoft.azure.functions.worker.broker.ParameterResolver.resolve(ParameterResolver.java:42) 
at com.microsoft.azure.functions.worker.broker.JavaMethodExecutor.execute(JavaMethodExecutor.java:52) 
at com.microsoft.azure.functions.worker.broker.JavaFunctionBroker.invokeMethod(JavaFunctionBroker.java:53) 
at com.microsoft.azure.functions.worker.handler.InvocationRequestHandler.execute(InvocationRequestHandler.java:33) 
at com.microsoft.azure.functions.worker.handler.InvocationRequestHandler.execute(InvocationRequestHandler.java:10) 
at com.microsoft.azure.functions.worker.handler.MessageHandler.handle(MessageHandler.java:45) 
at com.microsoft.azure.functions.worker.JavaWorkerClient$StreamingMessagePeer.lambda$onNext$0(JavaWorkerClient.java:92) 
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) 
at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) 
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) 
at java.lang.Thread.run(Thread.java:748)
```
### Environment Information

- **Micronaut Version:** 2.0.0-BUILD-SNAPSHOT
- **JDK Version:** 1.8

### Example Application

- https://github.com/mynecker/azure-function-demo-application

**Comment by graemerocher** [comment]
Thanks for the report will look into it
