### ISSUE TITLE
On hitting the APIs concurrently with runtime as Azure-function giving 500 error

### ISSUE THREAD

**Issue by kamalbhatia528** [micronaut-projects/micronaut-azure#611]
### Expected Behavior

I created a simple project with Azure-function and when I hit the GET request concurrently, its giving 500 for some APIs and 200 for some APIs, Its behaving randomly.

**Exception :**

```
 System.Private.CoreLib: Exception while executing function: Functions.ExampleTrigger. System.Private.CoreLib: Result: Failure
Exception: NoSuchBeanException: No bean of type [io.micronaut.core.convert.ConversionService] exists. Make sure the bean is not disabled by bean requirements (enable trace logging for 'io.micronaut.context.condition' to check) and if the bean is enabled then ensure the class is declared a bean and annotation processing is enabled (for Java and Kotlin the 'micronaut-inject-java' dependency should be configured as an annotation processor).
Stack: io.micronaut.context.exceptions.NoSuchBeanException: No bean of type [io.micronaut.core.convert.ConversionService] exists. Make sure the bean is not disabled by bean requirements (enable trace logging for 'io.micronaut.context.condition' to check) and if the bean is enabled then ensure the class is declared a bean and annotation processing is enabled (for Java and Kotlin the 'micronaut-inject-java' dependency should be configured as an annotation processor).
[2024-01-03T05:04:13.541Z] 	at io.micronaut.context.DefaultBeanContext.newNoSuchBeanException(DefaultBeanContext.java:2773)
[2024-01-03T05:04:13.545Z] 	at io.micronaut.context.DefaultApplicationContext.newNoSuchBeanException(DefaultApplicationContext.java:304)
[2024-01-03T05:04:13.545Z] 	at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2735)
[2024-01-03T05:04:13.545Z] 	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:1729)
[2024-01-03T05:04:13.545Z] 	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:856)
[2024-01-03T05:04:13.545Z] 	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:848)
[2024-01-03T05:04:13.546Z] 	at io.micronaut.azure.function.http.HttpRequestMessageHandler.<init>(HttpRequestMessageHandler.java:40)
[2024-01-03T05:04:13.546Z] 	at io.micronaut.azure.function.http.HttpHandler.<init>(HttpHandler.java:38)
[2024-01-03T05:04:13.546Z] 	at io.micronaut.azure.function.http.AzureHttpFunction.<init>(AzureHttpFunction.java:81)
[2024-01-03T05:04:13.546Z] 	at io.micronaut.azure.function.http.AzureHttpFunction.<init>(AzureHttpFunction.java:65)
[2024-01-03T05:04:13.546Z] 	at com.example.Function.<init>(Function.java:10)
[2024-01-03T05:04:13.547Z] 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[2024-01-03T05:04:13.547Z] 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
[2024-01-03T05:04:13.548Z] 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[2024-01-03T05:04:13.549Z] 	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
[2024-01-03T05:04:13.549Z] 	at java.base/java.lang.reflect.ReflectAccess.newInstance(ReflectAccess.java:128)
[2024-01-03T05:04:13.550Z] 	at java.base/jdk.internal.reflect.ReflectionFactory.newInstance(ReflectionFactory.java:347)
[2024-01-03T05:04:13.551Z] 	at java.base/java.lang.Class.newInstance(Class.java:645)
[2024-01-03T05:04:13.555Z] 	at com.microsoft.azure.functions.worker.broker.JavaFunctionBroker$1.getInstance(JavaFunctionBroker.java:45)
``` 

https://micronaut.io/launch/?type=DEFAULT&name=demo&package=com.example&javaVersion=JDK_17&lang=JAVA&build=GRADLE&test=SPOCK&features=azure-function&version=4.2.2&activity=create

### Actual Behaviour

This error should not come and work succesfully with 200 for concurrent requests as well.

### Steps To Reproduce

Use this project
https://micronaut.io/launch/?type=DEFAULT&name=demo&package=com.example&javaVersion=JDK_17&lang=JAVA&build=GRADLE&test=SPOCK&features=azure-function&version=4.2.2

### Environment Information

Windows
JDK17

### Example Application

https://micronaut.io/launch/?type=DEFAULT&name=demo&package=com.example&javaVersion=JDK_17&lang=JAVA&build=GRADLE&test=SPOCK&features=azure-function&version=4.2.2

### Version

4.2.2

**Comment by timyates** [comment]
How are you running your concurrent test?

**Comment by kamalbhatia528** [comment]
@timyates , I am hitting the concurrent requests by the script, Its just like you have to hit the same url at same time.

**Comment by timyates** [comment]
Which script?

How are you deploying the function?

A link to micronaut launch is not enough for me to easily reproduce what your are seeing locally on my machine

**Comment by kamalbhatia528** [comment]
I am simply running this by using azure function core tools command, 
./gradlew azureFunctionsRun

I have written the code to hit the same request asynchronously , you can use any tools whichever you want
Hope this answer your doubt

**Comment by timyates** [comment]
@kamalbhatia528 Confirmed as a bug since Micronaut 4.0.0... Thanks for reporting, I'm investigating
