### ISSUE TITLE
Blocking error with the vault config client between Azure client version 5.3.1 and 5.4.0

### ISSUE THREAD

**Issue by wcom939** [micronaut-projects/micronaut-azure#702]
### Expected Behavior

with micronaut gradle parent 4.3.8 and 4.4.0, the secrets are loaded successfully in vault when a controller rest call is made

### Actual Behaviour

with micronaut gradle parent 4.4.0 and later, the secret loading throws an error, when the secret is referenced in code by the controller (not on startup, but when a REST API is called that references the environment variable loaded from a secret)

```java
21:18:20.967 [default-nioEventLoopGroup-2-6] ERROR c.a.c.i.AccessTokenCache - {"az.sdk.message":"Failed to acquire a new access token.","exception":"DefaultAzureCredential authentication failed. ---> ManagedIdentityCredential authentication failed. Error Details: block()/blockFirst()/blockLast() are blocking, which is not supported in thread default-nioEventLoopGroup-2-6"}
21:18:20.969 [default-nioEventLoopGroup-2-6] ERROR c.azure.core.http.policy.RetryPolicy - {"az.sdk.message":"Retry attempts have been exhausted.","exception":"DefaultAzureCredential authentication failed. ---> ManagedIdentityCredential authentication failed. Error Details: block()/blockFirst()/blockLast() are blocking, which is not supported in thread default-nioEventLoopGroup-2-6","tryCount":3}
21:18:20.970 [default-nioEventLoopGroup-2-6] ERROR c.azure.core.http.policy.RetryPolicy - DefaultAzureCredential authentication failed. ---> ManagedIdentityCredential authentication failed. Error Details: block()/blockFirst()/blockLast() are blocking, which is not supported in thread default-nioEventLoopGroup-2-6
21:18:20.980 [default-nioEventLoopGroup-2-6] ERROR i.m.http.server.RouteExecutor - Unexpected error occurred: DefaultAzureCredential authentication failed. ---> ManagedIdentityCredential authentication failed. Error Details: block()/blockFirst()/blockLast() are blocking, which is not supported in thread default-nioEventLoopGroup-2-6
com.azure.core.exception.ClientAuthenticationException: DefaultAzureCredential authentication failed. ---> ManagedIdentityCredential authentication failed. Error Details: block()/blockFirst()/blockLast() are blocking, which is not supported in thread default-nioEventLoopGroup-2-6
	at com.azure.identity.ChainedTokenCredential.getTokenSync(ChainedTokenCredential.java:125)
	at com.azure.core.implementation.AccessTokenCache.lambda$new$2(AccessTokenCache.java:63)
	at com.azure.core.implementation.AccessTokenCache.lambda$retrieveTokenSync$11(AccessTokenCache.java:228)
	at com.azure.core.implementation.AccessTokenCache.getTokenSync(AccessTokenCache.java:91)
	at com.azure.core.http.policy.BearerTokenAuthenticationPolicy.setAuthorizationHeaderHelperSync(BearerTokenAuthenticationPolicy.java:204)
	at com.azure.core.http.policy.BearerTokenAuthenticationPolicy.setAuthorizationHeaderSync(BearerTokenAuthenticationPolicy.java:191)
	at com.azure.security.keyvault.secrets.implementation.KeyVaultCredentialPolicy.authorizeRequestSync(KeyVaultCredentialPolicy.java:227)
	at com.azure.core.http.policy.BearerTokenAuthenticationPolicy.processSync(BearerTokenAuthenticationPolicy.java:153)
	at com.azure.core.http.HttpPipelineNextSyncPolicy.processSync(HttpPipelineNextSyncPolicy.java:53)
	at com.azure.core.http.policy.RetryPolicy.attemptSync(RetryPolicy.java:211)
	at com.azure.core.http.policy.RetryPolicy.attemptSync(RetryPolicy.java:224)
	at com.azure.core.http.policy.RetryPolicy.attemptSync(RetryPolicy.java:224)
	at com.azure.core.http.policy.RetryPolicy.attemptSync(RetryPolicy.java:224)
	at com.azure.core.http.policy.RetryPolicy.processSync(RetryPolicy.java:161)
	at com.azure.core.http.HttpPipelineNextSyncPolicy.processSync(HttpPipelineNextSyncPolicy.java:53)
	at com.azure.core.http.policy.AddHeadersPolicy.processSync(AddHeadersPolicy.java:66)
	at com.azure.core.http.HttpPipelineNextSyncPolicy.processSync(HttpPipelineNextSyncPolicy.java:53)
	at com.azure.core.http.policy.HttpPipelineSyncPolicy.processSync(HttpPipelineSyncPolicy.java:51)
	at com.azure.core.http.policy.UserAgentPolicy.processSync(UserAgentPolicy.java:174)
	at com.azure.core.http.HttpPipelineNextSyncPolicy.processSync(HttpPipelineNextSyncPolicy.java:53)
	at com.azure.core.http.HttpPipeline.sendSync(HttpPipeline.java:138)
	at com.azure.core.implementation.http.rest.SyncRestProxy.send(SyncRestProxy.java:58)
	at com.azure.core.implementation.http.rest.SyncRestProxy.invoke(SyncRestProxy.java:79)
	at com.azure.core.implementation.http.rest.RestProxyBase.invoke(RestProxyBase.java:128)
	at com.azure.core.http.rest.RestProxy.invoke(RestProxy.java:97)
	at jdk.proxy2/jdk.proxy2.$Proxy7.getSecretSync(Unknown Source)
	at com.azure.security.keyvault.secrets.implementation.SecretClientImpl.getSecretWithResponse(SecretClientImpl.java:1133)
	at com.azure.security.keyvault.secrets.SecretClient.lambda$getSecretWithResponse$1(SecretClient.java:360)
	at com.azure.security.keyvault.secrets.SecretClient.callWithMappedException(SecretClient.java:1025)
	at com.azure.security.keyvault.secrets.SecretClient.getSecretWithResponse(SecretClient.java:359)
	at com.azure.security.keyvault.secrets.SecretClient.getSecret(SecretClient.java:296)
	at com.springerpub.sso.common.service.VaultService.getSecret(VaultService.java:36)
	at com.springerpub.sso.common.service.AuthOService.doesEmailExist(AuthOService.java:44)
	at com.springerpub.sso.controller.CreateNewAuthoUserController.createNewAuthoUser(CreateNewAuthoUserController.java:47)
	at com.springerpub.sso.controller.$CreateNewAuthoUserController$Definition$Exec.dispatch(Unknown Source)
	at io.micronaut.context.AbstractExecutableMethodsDefinition$DispatchedExecutableMethod.invokeUnsafe(AbstractExecutableMethodsDefinition.java:461)
	at io.micronaut.context.DefaultBeanContext$BeanContextUnsafeExecutionHandle.invokeUnsafe(DefaultBeanContext.java:4232)
	at io.micronaut.web.router.AbstractRouteMatch.execute(AbstractRouteMatch.java:271)
	at io.micronaut.http.server.RouteExecutor.executeRouteAndConvertBody(RouteExecutor.java:488)
	at io.micronaut.http.server.RouteExecutor.callRoute(RouteExecutor.java:478)
	at io.micronaut.http.server.RequestLifecycle.callRoute(RequestLifecycle.java:201)
	at io.micronaut.http.server.RequestLifecycle.executeRoute(RequestLifecycle.java:191)
	at io.micronaut.http.server.RequestLifecycle.lambda$normalFlow$1(RequestLifecycle.java:181)
	at io.micronaut.http.filter.FilterRunner.provideResponse(FilterRunner.java:272)
	at io.micronaut.http.filter.FilterRunner.filterRequest(FilterRunner.java:207)
	at io.micronaut.http.filter.FilterRunner.run(FilterRunner.java:158)
	at io.micronaut.http.filter.FilterRunner.run(FilterRunner.java:135)
	at io.micronaut.http.server.RequestLifecycle.runWithFilters(RequestLifecycle.java:357)
	at io.micronaut.http.server.RequestLifecycle.normalFlow(RequestLifecycle.java:181)
	at io.micronaut.http.server.netty.NettyRequestLifecycle.handleNormal(NettyRequestLifecycle.java:88)
	at io.micronaut.http.server.netty.RoutingInBoundHandler.accept(RoutingInBoundHandler.java:236)
	at io.micronaut.http.server.netty.websocket.NettyServerWebSocketUpgradeHandler.accept(NettyServerWebSocketUpgradeHandler.java:156)
	at io.micronaut.http.server.netty.handler.PipeliningServerHandler$OptimisticBufferingInboundHandler.read(PipeliningServerHandler.java:474)
	at io.micronaut.http.server.netty.handler.PipeliningServerHandler.channelRead(PipeliningServerHandler.java:213)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:93)
	at io.netty.handler.codec.http.websocketx.extensions.WebSocketServerExtensionHandler.channelRead(WebSocketServerExtensionHandler.java:88)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:289)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)
	Suppressed: com.azure.core.exception.ClientAuthenticationException: DefaultAzureCredential authentication failed. ---> ManagedIdentityCredential authentication failed. Error Details: block()/blockFirst()/blockLast() are blocking, which is not supported in thread default-nioEventLoopGroup-2-6
		at com.azure.identity.ChainedTokenCredential.getTokenSync(ChainedTokenCredential.java:125)
		at com.azure.core.implementation.AccessTokenCache.lambda$new$2(AccessTokenCache.java:63)
		at com.azure.core.implementation.AccessTokenCache.lambda$retrieveTokenSync$11(AccessTokenCache.java:228)
		at com.azure.core.implementation.AccessTokenCache.getTokenSync(AccessTokenCache.java:91)
		at com.azure.core.http.policy.BearerTokenAuthenticationPolicy.setAuthorizationHeaderHelperSync(BearerTokenAuthenticationPolicy.java:204)
		at com.azure.core.http.policy.BearerTokenAuthenticationPolicy.setAuthorizationHeaderSync(BearerTokenAuthenticationPolicy.java:191)
		at com.azure.security.keyvault.secrets.implementation.KeyVaultCredentialPolicy.authorizeRequestSync(KeyVaultCredentialPolicy.java:227)
		at com.azure.core.http.policy.BearerTokenAuthenticationPolicy.processSync(BearerTokenAuthenticationPolicy.java:153)
		at com.azure.core.http.HttpPipelineNextSyncPolicy.processSync(HttpPipelineNextSyncPolicy.java:53)
		at com.azure.core.http.policy.RetryPolicy.attemptSync(RetryPolicy.java:211)
		... 73 common frames omitted
	Caused by: java.lang.IllegalStateException: block()/blockFirst()/blockLast() are blocking, which is not supported in thread default-nioEventLoopGroup-2-6
		at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:87)
		at reactor.core.publisher.Mono.block(Mono.java:1779)
		at com.azure.core.credential.TokenCredential.getTokenSync(TokenCredential.java:110)
		at com.azure.identity.ChainedTokenCredential.getTokenSync(ChainedTokenCredential.java:120)
		... 82 common frames omitted
	Suppressed: com.azure.core.exception.ClientAuthenticationException: DefaultAzureCredential authentication failed. ---> ManagedIdentityCredential authentication failed. Error Details: block()/blockFirst()/blockLast() are blocking, which is not supported in thread default-nioEventLoopGroup-2-6
	Caused by: java.lang.IllegalStateException: block()/blockFirst()/blockLast() are blocking, which is not supported in thread default-nioEventLoopGroup-2-6

		at com.azure.identity.ChainedTokenCredential.getTokenSync(ChainedTokenCredential.java:125)
		at com.azure.core.implementation.AccessTokenCache.lambda$new$2(AccessTokenCache.java:63)
		at com.azure.core.implementation.AccessTokenCache.lambda$retrieveTokenSync$11(AccessTokenCache.java:228)
		at com.azure.core.implementation.AccessTokenCache.getTokenSync(AccessTokenCache.java:91)
		at com.azure.core.http.policy.BearerTokenAuthenticationPolicy.setAuthorizationHeaderHelperSync(BearerTokenAuthenticationPolicy.java:204)
		at com.azure.core.http.policy.BearerTokenAuthenticationPolicy.setAuthorizationHeaderSync(BearerTokenAuthenticationPolicy.java:191)
		at com.azure.security.keyvault.secrets.implementation.KeyVaultCredentialPolicy.authorizeRequestSync(KeyVaultCredentialPolicy.java:227)
		at com.azure.core.http.policy.BearerTokenAuthenticationPolicy.processSync(BearerTokenAuthenticationPolicy.java:153)
		at com.azure.core.http.HttpPipelineNextSyncPolicy.processSync(HttpPipelineNextSyncPolicy.java:53)
		at com.azure.core.http.policy.RetryPolicy.attemptSync(RetryPolicy.java:211)
		... 74 common frames omitted
	Caused by: java.lang.IllegalStateException: block()/blockFirst()/blockLast() are blocking, which is not supported in thread default-nioEventLoopGroup-2-6
		at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:87)
		at reactor.core.publisher.Mono.block(Mono.java:1779)
		at com.azure.core.credential.TokenCredential.getTokenSync(TokenCredential.java:110)
		at com.azure.identity.ChainedTokenCredential.getTokenSync(ChainedTokenCredential.java:120)
		... 83 common frames omitted
	Suppressed: com.azure.core.exception.ClientAuthenticationException: DefaultAzureCredential authentication failed. ---> ManagedIdentityCredential authentication failed. Error Details: block()/blockFirst()/blockLast() are blocking, which is not supported in thread default-nioEventLoopGroup-2-6
		at com.azure.identity.ChainedTokenCredential.getTokenSync(ChainedTokenCredential.java:125)
		at com.azure.core.implementation.AccessTokenCache.lambda$new$2(AccessTokenCache.java:63)
		at com.azure.core.implementation.AccessTokenCache.lambda$retrieveTokenSync$11(AccessTokenCache.java:228)
		at com.azure.core.implementation.AccessTokenCache.getTokenSync(AccessTokenCache.java:91)
		at com.azure.core.http.policy.BearerTokenAuthenticationPolicy.setAuthorizationHeaderHelperSync(BearerTokenAuthenticationPolicy.java:204)
		at com.azure.core.http.policy.BearerTokenAuthenticationPolicy.setAuthorizationHeaderSync(BearerTokenAuthenticationPolicy.java:191)
		at com.azure.security.keyvault.secrets.implementation.KeyVaultCredentialPolicy.authorizeRequestSync(KeyVaultCredentialPolicy.java:227)
		at com.azure.core.http.policy.BearerTokenAuthenticationPolicy.processSync(BearerTokenAuthenticationPolicy.java:153)
		at com.azure.core.http.HttpPipelineNextSyncPolicy.processSync(HttpPipelineNextSyncPolicy.java:53)
		at com.azure.core.http.policy.RetryPolicy.attemptSync(RetryPolicy.java:211)
		... 75 common frames omitted
	Caused by: java.lang.IllegalStateException: block()/blockFirst()/blockLast() are blocking, which is not supported in thread default-nioEventLoopGroup-2-6
		at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:87)
		at reactor.core.publisher.Mono.block(Mono.java:1779)
		at com.azure.core.credential.TokenCredential.getTokenSync(TokenCredential.java:110)
		at com.azure.identity.ChainedTokenCredential.getTokenSync(ChainedTokenCredential.java:120)
		... 84 common frames omitted
Caused by: java.lang.IllegalStateException: block()/blockFirst()/blockLast() are blocking, which is not supported in thread default-nioEventLoopGroup-2-6
	at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:87)
	at reactor.core.publisher.Mono.block(Mono.java:1779)
Caused by: java.lang.IllegalStateException: block()/blockFirst()/blockLast() are blocking, which is not supported in thread default-nioEventLoopGroup-2-6

	at com.azure.core.credential.TokenCredential.getTokenSync(TokenCredential.java:110)
	at com.azure.identity.ChainedTokenCredential.getTokenSync(ChainedTokenCredential.java:120)
	... 85 common frames omitted
21:18:20.994 [ForkJoinPool.commonPool-worker-13] WARN  c.m.a.m.ConfidentialClientApplication - [Correlation ID: 936a1e6e-2968-454a-a2f1-c7755bf41362] Execution of class com.microsoft.aad.msal4j.AcquireTokenByClientCredentialSupplier failed: java.util.concurrent.ExecutionException: com.azure.identity.CredentialUnavailableException: ManagedIdentityCredential authentication unavailable. Connection to IMDS endpoint cannot be established, Network is unreachable: no further information.

``` 

### Steps To Reproduce

1. Setup a default project that loads a secret from a vault via the micronaut config/bootstrap.yml method.
2. Setup a hello world controller
3. Create a private variable in the controller, reference it using the @Value annotation to match the injected secret
4. Reference that variable in the controller method
5. Start the application in debug mode
6. make the rest call

### Environment Information

Windows 11 and OSX
JDK 17

### Version

platform version 4.4.0

**Comment by graemerocher** [comment]
not sure this is a bug, it has actually revealed an issue since you are blocking the event loop. The solution is to add `@ExecuteOn(TaskExecutors.BLOCKING)` on the `com.springerpub.sso.controller.CreateNewAuthoUserController.createNewAuthoUser` method or on the controller

**Comment by wcom939** [comment]
thanks that fixed it!
